apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: accelerator-detector-script
  files:
  - detect-and-label.py=scripts/detect-and-label.py

resources:
  - service_account.yaml
  - gpu-daemonset.yaml
  - cpu-daemonset.yaml
