// MIT License
//
// Copyright (c) 2025 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package aimservice

import (
	"context"
	"fmt"
	"strings"

	aimv1alpha1 "github.com/amd-enterprise-ai/aim-engine/api/v1alpha1"
	"github.com/amd-enterprise-ai/aim-engine/internal/constants"
	controllerutils "github.com/amd-enterprise-ai/aim-engine/internal/controller/utils"
	"github.com/amd-enterprise-ai/aim-engine/internal/utils"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func fetchKVCache(
	ctx context.Context,
	c client.Client,
	service *aimv1alpha1.AIMService,
) controllerutils.FetchResult[*aimv1alpha1.AIMKVCache] {
	if service.Spec.KVCache == nil {
		return controllerutils.FetchResult[*aimv1alpha1.AIMKVCache]{}
	}

	name := service.Spec.KVCache.Name
	if name == "" {
		name = fmt.Sprintf("kvcache-%s", service.Namespace)
	}

	return controllerutils.Fetch(ctx, c, client.ObjectKey{
		Namespace: service.Namespace,
		Name:      name,
	}, &aimv1alpha1.AIMKVCache{})
}

func planKVCache(service *aimv1alpha1.AIMService, obs ServiceObservation) client.Object {
	if service.Spec.KVCache == nil {
		return nil
	}

	// Don't create if already exists (regardless of spec mismatch)
	if obs.kvCache.OK() && obs.kvCache.Value != nil {
		return nil
	}

	// Don't create if there was a fetch error (other than NotFound)
	if obs.kvCache.IsNotFound() {
		return buildKVCache(service)
	}

	return nil
}

func buildKVCache(service *aimv1alpha1.AIMService) *aimv1alpha1.AIMKVCache {
	spec := service.Spec.KVCache

	name := spec.Name
	if name == "" {
		name = fmt.Sprintf("kvcache-%s", service.Namespace)
	}

	kvCacheType := spec.Type
	if kvCacheType == "" {
		kvCacheType = "redis"
	}

	kvc := &aimv1alpha1.AIMKVCache{
		TypeMeta: metav1.TypeMeta{
			APIVersion: aimv1alpha1.GroupVersion.String(),
			Kind:       "AIMKVCache",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: service.Namespace,
			Labels: map[string]string{
				constants.LabelKeyOrigin: constants.LabelValueOriginAutoGenerated,
			},
		},
		Spec: aimv1alpha1.AIMKVCacheSpec{
			KVCacheType: kvCacheType,
			Image:       spec.Image,
			Env:         spec.Env,
			Storage:     spec.Storage,
			Resources:   spec.Resources,
		},
	}

	return kvc
}

// fetchLMCacheConfigMap fetches the LMCache configuration ConfigMap.
func fetchLMCacheConfigMap(
	ctx context.Context,
	c client.Client,
	service *aimv1alpha1.AIMService,
) controllerutils.FetchResult[*corev1.ConfigMap] {
	name, err := generateLMCacheConfigMapName(service.Name, service.Namespace)
	if err != nil {
		return controllerutils.FetchResult[*corev1.ConfigMap]{Error: err}
	}
	return controllerutils.Fetch(ctx, c, client.ObjectKey{
		Namespace: service.Namespace,
		Name:      name,
	}, &corev1.ConfigMap{})
}

func generateLMCacheConfigMapName(serviceName, namespace string) (string, error) {
	return utils.GenerateDerivedName([]string{"lmcache", serviceName}, utils.WithHashSource(namespace))
}

// planLMCacheConfigMap creates the LMCache ConfigMap if KVCache is ready and ConfigMap doesn't exist.
func planLMCacheConfigMap(service *aimv1alpha1.AIMService, obs ServiceObservation) client.Object {
	if service.Spec.KVCache == nil {
		return nil
	}

	// Don't create if KVCache isn't ready
	if obs.kvCache.Value == nil || obs.kvCache.Value.Status.Status != constants.AIMStatusReady {
		return nil
	}

	// Don't create if already exists
	if obs.kvCacheConfigMap.OK() && obs.kvCacheConfigMap.Value != nil {
		return nil
	}

	// Only create if NotFound (not on other errors)
	if !obs.kvCacheConfigMap.IsNotFound() {
		return nil
	}

	return buildLMCacheConfigMap(service, obs.kvCache.Value)
}

func buildLMCacheConfigMap(service *aimv1alpha1.AIMService, kvCache *aimv1alpha1.AIMKVCache) *corev1.ConfigMap {
	configMapName, err := generateLMCacheConfigMapName(service.Name, service.Namespace)
	if err != nil {
		return nil
	}

	// Build service URL from KVCache endpoint
	serviceURL := kvCache.Status.Endpoint
	if serviceURL == "" {
		// Fallback: construct from service name
		serviceURL = fmt.Sprintf("redis://%s.%s.svc.cluster.local:6379",
			kvCache.Status.ServiceName, kvCache.Namespace)
	}

	var lmcacheConfig string
	if service.Spec.KVCache.LMCacheConfig != "" {
		// Use custom config, replacing {SERVICE_URL} placeholder
		lmcacheConfig = strings.ReplaceAll(service.Spec.KVCache.LMCacheConfig, "{SERVICE_URL}", serviceURL)
	} else {
		// Use default config
		lmcacheConfig = fmt.Sprintf(`local_cpu: true
chunk_size: 50
max_local_cpu_size: 1.0
remote_url: %q
remote_serde: "naive"
`, serviceURL)
	}

	return &corev1.ConfigMap{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "ConfigMap",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      configMapName,
			Namespace: service.Namespace,
			Labels: map[string]string{
				constants.LabelK8sManagedBy: constants.LabelValueManagedBy,
			},
		},
		Data: map[string]string{
			"lmcache_config.yaml": lmcacheConfig,
		},
	}
}
