#!/usr/bin/env bash
#
# patch-helm-chart.sh - Post-process the kubebuilder-generated Helm chart
#
# This script applies customizations to the Helm chart generated by
# kubebuilder's helm/v2-alpha plugin. It handles:
# - Namespace templating (fix hardcoded aim-system)
# - imagePullSecrets support for the manager deployment
# - CRD removal (distributed separately)
# - Custom values.yaml and templates overlay
#
# Usage: ./hack/patch-helm-chart.sh
#
set -euo pipefail

CHART_DIR="dist/chart"
MANAGER_YAML="${CHART_DIR}/templates/manager/manager.yaml"

echo "Patching Helm chart at ${CHART_DIR}..."

# ------------------------------------------------------------------------------
# Fix hardcoded namespace in kubebuilder-generated templates
# Known limitation of helm/v2-alpha plugin
# ------------------------------------------------------------------------------
echo "  - Fixing hardcoded namespace references..."
find "${CHART_DIR}/templates" -name '*.yaml' -exec \
    sed -i 's/namespace: aim-system/namespace: {{ .Release.Namespace }}/g' {} \;

# ------------------------------------------------------------------------------
# Add imagePullSecrets support to manager deployment
# Injects templating after serviceAccountName to allow pulling from private registries
# ------------------------------------------------------------------------------
echo "  - Adding imagePullSecrets support to manager deployment..."
if [[ -f "${MANAGER_YAML}" ]]; then
    sed -i '/serviceAccountName: aim-engine-controller-manager/a\            {{- with .Values.manager.imagePullSecrets }}' "${MANAGER_YAML}"
    sed -i '/{{- with .Values.manager.imagePullSecrets }}/a\            imagePullSecrets:' "${MANAGER_YAML}"
    sed -i '/imagePullSecrets:$/a\              {{- toYaml . | nindent 14 }}' "${MANAGER_YAML}"
    sed -i '/{{- toYaml . | nindent 14 }}/a\            {{- end }}' "${MANAGER_YAML}"
else
    echo "    Warning: ${MANAGER_YAML} not found, skipping imagePullSecrets patch"
fi

# ------------------------------------------------------------------------------
# Remove CRDs from chart - they are distributed separately
# This allows independent CRD lifecycle management
# ------------------------------------------------------------------------------
echo "  - Removing CRDs from chart (distributed separately)..."
rm -rf "${CHART_DIR}/templates/crd"

# ------------------------------------------------------------------------------
# Apply custom values.yaml if it exists
# Since dist/ is gitignored, we need persistent config in config/helm/
# ------------------------------------------------------------------------------
if [[ -f config/helm/values.yaml ]]; then
    echo "  - Applying custom values.yaml..."
    cp config/helm/values.yaml "${CHART_DIR}/values.yaml"
fi

# ------------------------------------------------------------------------------
# Copy custom templates if they exist
# Allows adding or overriding templates without modifying generated ones
# ------------------------------------------------------------------------------
if [[ -d config/helm/templates ]]; then
    echo "  - Copying custom templates..."
    cp -r config/helm/templates/* "${CHART_DIR}/templates/"
fi

echo "Helm chart patching complete."
