apiVersion: aim.eai.amd.com/v1alpha1
kind: AIMClusterModelSource
metadata:
  name: ghcr-models
spec:
  registry: ghcr.io
  syncInterval: 1h
  maxModels: 10

  # Reference to pull secret (must exist in operator namespace)
  imagePullSecrets:
    - name: ghcr-regcred

  images:
    - "amdenterpriseai/aim-qwen-qwen3-32b:0.8.4"