// MIT License
//
// Copyright (c) 2025 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package aimmodel

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	aimv1alpha1 "github.com/amd-enterprise-ai/aim-engine/api/v1alpha1"
	"github.com/amd-enterprise-ai/aim-engine/internal/aimservicetemplate"
	"github.com/amd-enterprise-ai/aim-engine/internal/constants"
)

// templateBuilderOutputs contains the common parts built by buildTemplateComponents
type templateBuilderOutputs struct {
	Name   string
	Labels map[string]string
	Spec   aimv1alpha1.AIMServiceTemplateSpecCommon
}

// buildTemplateComponents builds the common components (name, labels, spec) for a service template
func buildTemplateComponents(modelName string, modelSpec aimv1alpha1.AIMModelSpec, deployment aimv1alpha1.RecommendedDeployment) templateBuilderOutputs {
	// Generate template name using the specified format (includes modelName in hash for uniqueness)
	templateName := aimservicetemplate.GenerateTemplateName(modelName, modelSpec.Image, deployment)

	// Build common spec
	commonSpec := aimv1alpha1.AIMServiceTemplateSpecCommon{
		ModelName:          modelName,
		ImagePullSecrets:   modelSpec.ImagePullSecrets,
		ServiceAccountName: modelSpec.ServiceAccountName,
	}

	// Set runtime parameters from deployment
	if deployment.Metric != "" {
		metric := aimv1alpha1.AIMMetric(deployment.Metric)
		commonSpec.Metric = &metric
	}
	if deployment.Precision != "" {
		precision := aimv1alpha1.AIMPrecision(deployment.Precision)
		commonSpec.Precision = &precision
	}
	if deployment.GPUModel != "" && deployment.GPUCount > 0 {
		commonSpec.GpuSelector = &aimv1alpha1.AIMGpuSelector{
			Model: deployment.GPUModel,
			Count: deployment.GPUCount,
		}
	}

	// Common labels
	labels := map[string]string{
		constants.LabelKeyModel:  modelName,
		constants.LabelKeyOrigin: constants.LabelValueOriginAutoGenerated,
	}

	return templateBuilderOutputs{
		Name:   templateName,
		Labels: labels,
		Spec:   commonSpec,
	}
}

// buildClusterServiceTemplate creates a cluster-scoped service template from model and deployment info.
func buildClusterServiceTemplate(
	model *aimv1alpha1.AIMClusterModel,
	deployment aimv1alpha1.RecommendedDeployment,
) *aimv1alpha1.AIMClusterServiceTemplate {
	components := buildTemplateComponents(model.Name, model.Spec, deployment)
	return &aimv1alpha1.AIMClusterServiceTemplate{
		ObjectMeta: metav1.ObjectMeta{
			Name:   components.Name,
			Labels: components.Labels,
		},
		Spec: aimv1alpha1.AIMClusterServiceTemplateSpec{
			AIMServiceTemplateSpecCommon: components.Spec,
		},
	}
}

// buildServiceTemplate creates a namespace-scoped service template from model and deployment info.
func buildServiceTemplate(
	model *aimv1alpha1.AIMModel,
	deployment aimv1alpha1.RecommendedDeployment,
) *aimv1alpha1.AIMServiceTemplate {
	components := buildTemplateComponents(model.Name, model.Spec, deployment)
	return &aimv1alpha1.AIMServiceTemplate{
		ObjectMeta: metav1.ObjectMeta{
			Name:      components.Name,
			Namespace: model.Namespace,
			Labels:    components.Labels,
		},
		Spec: aimv1alpha1.AIMServiceTemplateSpec{
			AIMServiceTemplateSpecCommon: components.Spec,
		},
	}
}
