/*
MIT License

Copyright (c) 2025 Advanced Micro Devices, Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

package aimmodel

import (
	"errors"
	"testing"

	"k8s.io/utils/ptr"

	aimv1alpha1 "github.com/amd-enterprise-ai/aim-engine/api/v1alpha1"
	"github.com/amd-enterprise-ai/aim-engine/internal/constants"
	controllerutils "github.com/amd-enterprise-ai/aim-engine/internal/controller/utils"
)

const (
	defaultGpuModel = "MI300X"
)

// ============================================================================
// HELPER FUNCTIONS TESTS
// ============================================================================

func TestShouldCreateTemplates(t *testing.T) {
	tests := []struct {
		name      string
		modelSpec aimv1alpha1.AIMModelSpec
		config    *aimv1alpha1.AIMRuntimeConfigCommon
		expected  bool
	}{
		{
			name: "default - should create templates",
			modelSpec: aimv1alpha1.AIMModelSpec{
				Image: "test:latest",
			},
			config:   nil,
			expected: true,
		},
		{
			name: "auto discovery disabled in config",
			modelSpec: aimv1alpha1.AIMModelSpec{
				Image: "test:latest",
			},
			config: &aimv1alpha1.AIMRuntimeConfigCommon{
				Model: &aimv1alpha1.AIMModelConfig{
					AutoDiscovery: ptr.To(false),
				},
			},
			expected: false,
		},
		{
			name: "auto discovery enabled in config",
			modelSpec: aimv1alpha1.AIMModelSpec{
				Image: "test:latest",
			},
			config: &aimv1alpha1.AIMRuntimeConfigCommon{
				Model: &aimv1alpha1.AIMModelConfig{
					AutoDiscovery: ptr.To(true),
				},
			},
			expected: true,
		},
		{
			name: "autoCreateTemplates disabled in model spec",
			modelSpec: aimv1alpha1.AIMModelSpec{
				Image: "test:latest",
				Discovery: &aimv1alpha1.AIMModelDiscoveryConfig{
					AutoCreateTemplates: ptr.To(false),
				},
			},
			config:   nil,
			expected: false,
		},
		{
			name: "autoCreateTemplates enabled in model spec",
			modelSpec: aimv1alpha1.AIMModelSpec{
				Image: "test:latest",
				Discovery: &aimv1alpha1.AIMModelDiscoveryConfig{
					AutoCreateTemplates: ptr.To(true),
				},
			},
			config:   nil,
			expected: true,
		},
		{
			name: "model spec overrides config",
			modelSpec: aimv1alpha1.AIMModelSpec{
				Image: "test:latest",
				Discovery: &aimv1alpha1.AIMModelDiscoveryConfig{
					AutoCreateTemplates: ptr.To(false),
				},
			},
			config: &aimv1alpha1.AIMRuntimeConfigCommon{
				Model: &aimv1alpha1.AIMModelConfig{
					AutoDiscovery: ptr.To(true),
				},
			},
			expected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := shouldCreateTemplates(tt.modelSpec, tt.config)
			if result != tt.expected {
				t.Errorf("shouldCreateTemplates() = %v, want %v", result, tt.expected)
			}
		})
	}
}

func TestBuildTemplateComponents(t *testing.T) {
	modelSpec := aimv1alpha1.AIMModelSpec{
		Image: "test-image:v1",
	}
	deployment := aimv1alpha1.RecommendedDeployment{
		Metric:    "throughput",
		Precision: "fp16",
		GPUModel:  defaultGpuModel,
		GPUCount:  2,
	}

	result := buildTemplateComponents("test-model", modelSpec, deployment)

	if result.Name == "" {
		t.Error("expected template name to be set")
	}

	if result.Spec.ModelName != "test-model" {
		t.Errorf("expected ModelName=test-model, got %s", result.Spec.ModelName)
	}

	if result.Spec.Metric == nil || string(*result.Spec.Metric) != "throughput" {
		t.Error("expected Metric=throughput")
	}

	if result.Spec.Precision == nil || string(*result.Spec.Precision) != "fp16" {
		t.Error("expected Precision=fp16")
	}

	if result.Spec.GpuSelector == nil {
		t.Fatal("expected GpuSelector to be set")
	}
	if result.Spec.GpuSelector.Model != defaultGpuModel {
		t.Errorf("expected GpuSelector.Model=MI300X, got %s", result.Spec.GpuSelector.Model)
	}
	if result.Spec.GpuSelector.Count != 2 {
		t.Errorf("expected GpuSelector.Count=2, got %d", result.Spec.GpuSelector.Count)
	}

	if result.Labels[constants.LabelKeyAutoGenerated] != constants.LabelValueAutoGenerated {
		t.Error("expected auto-generated label")
	}
	if result.Labels[constants.LabelKeyModelName] != "test-model" {
		t.Error("expected model name label")
	}
}

func TestBuildTemplateComponents_MinimalDeployment(t *testing.T) {
	modelSpec := aimv1alpha1.AIMModelSpec{
		Image: "test-image:v1",
	}
	deployment := aimv1alpha1.RecommendedDeployment{}

	result := buildTemplateComponents("test-model", modelSpec, deployment)

	if result.Spec.Metric != nil {
		t.Error("expected Metric=nil for empty deployment")
	}
	if result.Spec.Precision != nil {
		t.Error("expected Precision=nil for empty deployment")
	}
	if result.Spec.GpuSelector != nil {
		t.Error("expected GpuSelector=nil for empty deployment")
	}
}

// ============================================================================
// OBSERVE TESTS
// ============================================================================

func TestObserveClusterModelServiceTemplate(t *testing.T) {
	existingTemplates := []aimv1alpha1.AIMClusterServiceTemplate{
		{},
		{},
	}
	fetchResult := clusterModelServiceTemplateFetchResult{
		clusterServiceTemplates: existingTemplates,
	}
	clusterModel := aimv1alpha1.AIMClusterModel{
		Spec: aimv1alpha1.AIMModelSpec{
			Image: "test:latest",
		},
	}
	config := &aimv1alpha1.AIMRuntimeConfigCommon{
		Model: &aimv1alpha1.AIMModelConfig{},
	}

	obs := observeClusterModelServiceTemplate(fetchResult, clusterModel, config)

	if !obs.shouldCreateTemplates {
		t.Error("expected shouldCreateTemplates=true with default config")
	}
	if len(obs.existingTemplates) != 2 {
		t.Errorf("expected 2 existing templates, got %d", len(obs.existingTemplates))
	}
}

func TestObserveModelServiceTemplate(t *testing.T) {
	existingTemplates := []aimv1alpha1.AIMServiceTemplate{
		{},
	}
	fetchResult := modelServiceTemplateFetchResult{
		serviceTemplates: existingTemplates,
	}
	model := aimv1alpha1.AIMModel{
		Spec: aimv1alpha1.AIMModelSpec{
			Image: "test:latest",
		},
	}
	config := &aimv1alpha1.AIMRuntimeConfigCommon{
		Model: &aimv1alpha1.AIMModelConfig{},
	}

	obs := observeModelServiceTemplate(fetchResult, model, config)

	if !obs.shouldCreateTemplates {
		t.Error("expected shouldCreateTemplates=true with default config")
	}
	if len(obs.existingTemplates) != 1 {
		t.Errorf("expected 1 existing template, got %d", len(obs.existingTemplates))
	}
}

// ============================================================================
// PLAN TESTS
// ============================================================================

func TestPlanClusterModelServiceTemplates_ShouldNotCreate(t *testing.T) {
	templateObs := clusterModelServiceTemplateObservation{
		shouldCreateTemplates: false,
	}
	metadataObs := modelMetadataObservation{}
	clusterModel := aimv1alpha1.AIMClusterModel{}

	templates := planClusterModelServiceTemplates(templateObs, metadataObs, clusterModel)

	if len(templates) != 0 {
		t.Errorf("expected 0 templates when shouldCreateTemplates=false, got %d", len(templates))
	}
}

func TestPlanClusterModelServiceTemplates_MetadataError(t *testing.T) {
	templateObs := clusterModelServiceTemplateObservation{
		shouldCreateTemplates: true,
	}
	metadataObs := modelMetadataObservation{
		Error: errors.New("extraction failed"),
	}
	clusterModel := aimv1alpha1.AIMClusterModel{}

	templates := planClusterModelServiceTemplates(templateObs, metadataObs, clusterModel)

	if len(templates) != 0 {
		t.Errorf("expected 0 templates when metadata error, got %d", len(templates))
	}
}

func TestPlanClusterModelServiceTemplates_NoMetadata(t *testing.T) {
	templateObs := clusterModelServiceTemplateObservation{
		shouldCreateTemplates: true,
	}
	metadataObs := modelMetadataObservation{
		ExtractedMetadata: nil,
	}
	clusterModel := aimv1alpha1.AIMClusterModel{}

	templates := planClusterModelServiceTemplates(templateObs, metadataObs, clusterModel)

	if len(templates) != 0 {
		t.Errorf("expected 0 templates when no metadata, got %d", len(templates))
	}
}

func TestPlanClusterModelServiceTemplates_CreateTemplates(t *testing.T) {
	templateObs := clusterModelServiceTemplateObservation{
		shouldCreateTemplates: true,
	}
	metadataObs := modelMetadataObservation{
		ExtractedMetadata: &aimv1alpha1.ImageMetadata{
			Model: &aimv1alpha1.ModelMetadata{
				RecommendedDeployments: []aimv1alpha1.RecommendedDeployment{
					{
						Metric:    "throughput",
						Precision: "fp16",
						GPUModel:  defaultGpuModel,
						GPUCount:  1,
					},
					{
						Metric:    "latency",
						Precision: "fp32",
						GPUModel:  defaultGpuModel,
						GPUCount:  2,
					},
				},
			},
		},
	}
	clusterModel := aimv1alpha1.AIMClusterModel{
		Spec: aimv1alpha1.AIMModelSpec{
			Image: "test:latest",
		},
	}

	templates := planClusterModelServiceTemplates(templateObs, metadataObs, clusterModel)

	if len(templates) != 2 {
		t.Errorf("expected 2 templates, got %d", len(templates))
	}

	for _, tmpl := range templates {
		clusterTemplate, ok := tmpl.(*aimv1alpha1.AIMClusterServiceTemplate)
		if !ok {
			t.Fatal("expected AIMClusterServiceTemplate")
		}
		if clusterTemplate.Name == "" {
			t.Error("expected template name to be set")
		}
		if clusterTemplate.Labels[constants.LabelKeyAutoGenerated] != constants.LabelValueAutoGenerated {
			t.Error("expected auto-generated label")
		}
	}
}

func TestPlanModelServiceTemplates_CreateTemplates(t *testing.T) {
	templateObs := modelServiceTemplateObservation{
		shouldCreateTemplates: true,
	}
	metadataObs := modelMetadataObservation{
		ExtractedMetadata: &aimv1alpha1.ImageMetadata{
			Model: &aimv1alpha1.ModelMetadata{
				RecommendedDeployments: []aimv1alpha1.RecommendedDeployment{
					{
						Metric:   "throughput",
						GPUModel: defaultGpuModel,
						GPUCount: 1,
					},
				},
			},
		},
	}
	model := aimv1alpha1.AIMModel{
		Spec: aimv1alpha1.AIMModelSpec{
			Image: "test:latest",
		},
	}

	templates := planModelServiceTemplates(templateObs, metadataObs, model)

	if len(templates) != 1 {
		t.Errorf("expected 1 template, got %d", len(templates))
	}

	template, ok := templates[0].(*aimv1alpha1.AIMServiceTemplate)
	if !ok {
		t.Fatal("expected AIMServiceTemplate")
	}
	if template.Name == "" {
		t.Error("expected template name to be set")
	}
	if template.Namespace != model.Namespace {
		t.Errorf("expected namespace=%s, got %s", model.Namespace, template.Namespace)
	}
}

// ============================================================================
// PROJECT TESTS
// ============================================================================

func TestProjectModelStatusFromTemplates_NoTemplates(t *testing.T) {
	status := &aimv1alpha1.AIMModelStatus{}
	cm := controllerutils.NewConditionManager(nil)
	sh := controllerutils.NewStatusHelper(status, cm)

	projectModelStatusFromTemplates(status, sh, []aimv1alpha1.AIMServiceTemplateStatus{})

	if status.Status != "" {
		t.Errorf("expected status to remain empty when no templates, got %s", status.Status)
	}
}

func TestProjectModelStatusFromTemplates_AllReady(t *testing.T) {
	status := &aimv1alpha1.AIMModelStatus{}
	cm := controllerutils.NewConditionManager(nil)
	sh := controllerutils.NewStatusHelper(status, cm)

	templateStatuses := []aimv1alpha1.AIMServiceTemplateStatus{
		{Status: constants.AIMStatusReady},
		{Status: constants.AIMStatusReady},
	}

	projectModelStatusFromTemplates(status, sh, templateStatuses)

	if status.Status != constants.AIMStatusReady {
		t.Errorf("expected status=Ready, got %s", status.Status)
	}
}

func TestProjectModelStatusFromTemplates_AllFailed(t *testing.T) {
	status := &aimv1alpha1.AIMModelStatus{}
	cm := controllerutils.NewConditionManager(nil)
	sh := controllerutils.NewStatusHelper(status, cm)

	templateStatuses := []aimv1alpha1.AIMServiceTemplateStatus{
		{Status: constants.AIMStatusFailed},
		{Status: constants.AIMStatusDegraded},
	}

	projectModelStatusFromTemplates(status, sh, templateStatuses)

	if status.Status != constants.AIMStatusFailed {
		t.Errorf("expected status=Failed, got %s", status.Status)
	}
}

func TestProjectModelStatusFromTemplates_AllNotAvailable(t *testing.T) {
	status := &aimv1alpha1.AIMModelStatus{}
	cm := controllerutils.NewConditionManager(nil)
	sh := controllerutils.NewStatusHelper(status, cm)

	templateStatuses := []aimv1alpha1.AIMServiceTemplateStatus{
		{Status: constants.AIMStatusNotAvailable},
		{Status: constants.AIMStatusNotAvailable},
	}

	projectModelStatusFromTemplates(status, sh, templateStatuses)

	if status.Status != constants.AIMStatusDegraded {
		t.Errorf("expected status=Degraded, got %s", status.Status)
	}
}

func TestProjectModelStatusFromTemplates_SomeDegraded(t *testing.T) {
	status := &aimv1alpha1.AIMModelStatus{}
	cm := controllerutils.NewConditionManager(nil)
	sh := controllerutils.NewStatusHelper(status, cm)

	templateStatuses := []aimv1alpha1.AIMServiceTemplateStatus{
		{Status: constants.AIMStatusReady},
		{Status: constants.AIMStatusDegraded},
	}

	projectModelStatusFromTemplates(status, sh, templateStatuses)

	if status.Status != constants.AIMStatusDegraded {
		t.Errorf("expected status=Degraded, got %s", status.Status)
	}
}

func TestProjectModelStatusFromTemplates_SomeProgressing(t *testing.T) {
	status := &aimv1alpha1.AIMModelStatus{}
	cm := controllerutils.NewConditionManager(nil)
	sh := controllerutils.NewStatusHelper(status, cm)

	templateStatuses := []aimv1alpha1.AIMServiceTemplateStatus{
		{Status: constants.AIMStatusReady},
		{Status: constants.AIMStatusProgressing},
	}

	projectModelStatusFromTemplates(status, sh, templateStatuses)

	if status.Status != constants.AIMStatusProgressing {
		t.Errorf("expected status=Progressing, got %s", status.Status)
	}
}

func TestProjectModelStatusFromTemplates_Mixed(t *testing.T) {
	tests := []struct {
		name           string
		statuses       []aimv1alpha1.AIMServiceTemplateStatus
		expectedStatus constants.AIMStatus
	}{
		{
			name: "ready and pending",
			statuses: []aimv1alpha1.AIMServiceTemplateStatus{
				{Status: constants.AIMStatusReady},
				{Status: constants.AIMStatusPending},
			},
			expectedStatus: constants.AIMStatusProgressing,
		},
		{
			name: "degraded and progressing",
			statuses: []aimv1alpha1.AIMServiceTemplateStatus{
				{Status: constants.AIMStatusDegraded},
				{Status: constants.AIMStatusProgressing},
			},
			expectedStatus: constants.AIMStatusDegraded,
		},
		{
			name: "failed, degraded, and ready",
			statuses: []aimv1alpha1.AIMServiceTemplateStatus{
				{Status: constants.AIMStatusFailed},
				{Status: constants.AIMStatusDegraded},
				{Status: constants.AIMStatusReady},
			},
			expectedStatus: constants.AIMStatusDegraded,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			status := &aimv1alpha1.AIMModelStatus{}
			cm := controllerutils.NewConditionManager(nil)
			sh := controllerutils.NewStatusHelper(status, cm)

			projectModelStatusFromTemplates(status, sh, tt.statuses)

			if status.Status != tt.expectedStatus {
				t.Errorf("expected status=%s, got %s", tt.expectedStatus, status.Status)
			}
		})
	}
}

// ============================================================================
// FETCH TESTS (for completeness)
// ============================================================================

func TestObserveClusterModelServiceTemplate_DisabledAutoDiscovery(t *testing.T) {
	fetchResult := clusterModelServiceTemplateFetchResult{}
	clusterModel := aimv1alpha1.AIMClusterModel{
		Spec: aimv1alpha1.AIMModelSpec{
			Image: "test:latest",
		},
	}
	config := &aimv1alpha1.AIMRuntimeConfigCommon{
		Model: &aimv1alpha1.AIMModelConfig{
			AutoDiscovery: ptr.To(false),
		},
	}

	obs := observeClusterModelServiceTemplate(fetchResult, clusterModel, config)

	if obs.shouldCreateTemplates {
		t.Error("expected shouldCreateTemplates=false when AutoDiscovery disabled")
	}
}

func TestObserveModelServiceTemplate_DisabledInModelSpec(t *testing.T) {
	fetchResult := modelServiceTemplateFetchResult{}
	model := aimv1alpha1.AIMModel{
		Spec: aimv1alpha1.AIMModelSpec{
			Image: "test:latest",
			Discovery: &aimv1alpha1.AIMModelDiscoveryConfig{
				AutoCreateTemplates: ptr.To(false),
			},
		},
	}
	config := &aimv1alpha1.AIMRuntimeConfigCommon{
		Model: &aimv1alpha1.AIMModelConfig{},
	}

	obs := observeModelServiceTemplate(fetchResult, model, config)

	if obs.shouldCreateTemplates {
		t.Error("expected shouldCreateTemplates=false when disabled in model spec")
	}
}
