/*
MIT License

Copyright (c) 2025 Advanced Micro Devices, Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

package aimmodel

import (
	"testing"

	aimv1alpha1 "github.com/amd-enterprise-ai/aim-engine/api/v1alpha1"
	"github.com/amd-enterprise-ai/aim-engine/internal/constants"
)

const (
	testGPUModel               = "MI300X"
	testModelName              = "test-model"
	testNamespace              = "test-namespace"
	testComponentImageMetadata = "ImageMetadata"
)

// ============================================================================
// BUILD TEMPLATE COMPONENT TESTS
// ============================================================================

func TestBuildTemplateComponents(t *testing.T) {
	modelSpec := aimv1alpha1.AIMModelSpec{
		Image: "test-image:v1",
	}
	deployment := aimv1alpha1.RecommendedDeployment{
		Metric:    "throughput",
		Precision: "fp16",
		GPUModel:  testGPUModel,
		GPUCount:  2,
	}

	result := buildTemplateComponents(testModelName, modelSpec, deployment)

	if result.Name == "" {
		t.Error("expected template name to be set")
	}

	if result.Spec.ModelName != testModelName {
		t.Errorf("expected ModelName=%s, got %s", testModelName, result.Spec.ModelName)
	}

	if result.Spec.Metric == nil || string(*result.Spec.Metric) != "throughput" {
		t.Error("expected Metric=throughput")
	}

	if result.Spec.Precision == nil || string(*result.Spec.Precision) != "fp16" {
		t.Error("expected Precision=fp16")
	}

	if result.Spec.Gpu == nil {
		t.Fatal("expected Gpu to be set")
	}
	if result.Spec.Gpu.Model != testGPUModel {
		t.Errorf("expected Gpu.Model=%s, got %v", testGPUModel, result.Spec.Gpu.Model)
	}
	if result.Spec.Gpu.Requests != 2 {
		t.Errorf("expected Gpu.Requests=2, got %d", result.Spec.Gpu.Requests)
	}

	if result.Labels[constants.LabelKeyOrigin] != constants.LabelValueOriginAutoGenerated {
		t.Error("expected origin=auto-generated label")
	}
	if result.Labels[constants.LabelKeyModel] != testModelName {
		t.Error("expected model label")
	}
}

func TestBuildTemplateComponents_MinimalDeployment(t *testing.T) {
	modelSpec := aimv1alpha1.AIMModelSpec{
		Image: "test-image:v1",
	}
	deployment := aimv1alpha1.RecommendedDeployment{}

	result := buildTemplateComponents(testModelName, modelSpec, deployment)

	if result.Spec.Metric != nil {
		t.Error("expected Metric=nil for empty deployment")
	}
	if result.Spec.Precision != nil {
		t.Error("expected Precision=nil for empty deployment")
	}
	if result.Spec.Gpu != nil {
		t.Error("expected Gpu=nil for empty deployment")
	}
}

// ============================================================================
// BUILD CLUSTER SERVICE TEMPLATE TESTS
// ============================================================================

func TestBuildClusterServiceTemplate(t *testing.T) {
	clusterModel := &aimv1alpha1.AIMClusterModel{
		Spec: aimv1alpha1.AIMModelSpec{
			Image: "test:latest",
		},
	}
	clusterModel.Name = "test-cluster-model"

	deployment := aimv1alpha1.RecommendedDeployment{
		Metric:    "throughput",
		Precision: "fp16",
		GPUModel:  testGPUModel,
		GPUCount:  1,
	}

	template := buildClusterServiceTemplate(clusterModel, deployment)

	if template.Name == "" {
		t.Error("expected template name to be set")
	}
	if template.Spec.ModelName != "test-cluster-model" {
		t.Errorf("expected ModelName=test-cluster-model, got %s", template.Spec.ModelName)
	}
	if template.Labels[constants.LabelKeyOrigin] != constants.LabelValueOriginAutoGenerated {
		t.Error("expected origin=auto-generated label")
	}
}

// ============================================================================
// BUILD SERVICE TEMPLATE TESTS
// ============================================================================

func TestBuildServiceTemplate(t *testing.T) {
	model := &aimv1alpha1.AIMModel{
		Spec: aimv1alpha1.AIMModelSpec{
			Image: "test:latest",
		},
	}
	model.Name = testModelName
	model.Namespace = testNamespace

	deployment := aimv1alpha1.RecommendedDeployment{
		Metric:   "throughput",
		GPUModel: testGPUModel,
		GPUCount: 1,
	}

	template := buildServiceTemplate(model, deployment)

	if template.Name == "" {
		t.Error("expected template name to be set")
	}
	if template.Namespace != testNamespace {
		t.Errorf("expected namespace=%s, got %s", testNamespace, template.Namespace)
	}
	if template.Spec.ModelName != testModelName {
		t.Errorf("expected ModelName=%s, got %s", testModelName, template.Spec.ModelName)
	}
	if template.Labels[constants.LabelKeyOrigin] != constants.LabelValueOriginAutoGenerated {
		t.Error("expected origin=auto-generated label")
	}
}

func TestBuildServiceTemplate_MultipleDeployments(t *testing.T) {
	model := &aimv1alpha1.AIMModel{
		Spec: aimv1alpha1.AIMModelSpec{
			Image: "test:latest",
		},
	}
	model.Name = testModelName
	model.Namespace = testNamespace

	deployments := []aimv1alpha1.RecommendedDeployment{
		{
			Metric:    "throughput",
			Precision: "fp16",
			GPUModel:  testGPUModel,
			GPUCount:  1,
		},
		{
			Metric:    "latency",
			Precision: "fp32",
			GPUModel:  testGPUModel,
			GPUCount:  2,
		},
	}

	// Build templates for each deployment
	for i, deployment := range deployments {
		template := buildServiceTemplate(model, deployment)

		if template.Name == "" {
			t.Errorf("template %d: expected name to be set", i)
		}
		if template.Spec.Metric == nil {
			t.Errorf("template %d: expected Metric to be set", i)
		}
		if template.Spec.Precision == nil {
			t.Errorf("template %d: expected Precision to be set", i)
		}
		if template.Spec.Gpu == nil || template.Spec.Gpu.Requests != deployment.GPUCount {
			t.Errorf("template %d: expected GPU count=%d", i, deployment.GPUCount)
		}
	}
}
