name: docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    if: vars.BUILD_DOCS == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: ./docs/redirect

      - name: Deploy redirect page to GitHub Pages
        run: mkdocs gh-deploy --force
        working-directory: ./docs/redirect
